# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

# Override values from the extended config or define new values
repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: hello-python

  # A short description of the repository that will show up on GitHub
  description: A python template repo

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams:
  # The permission to grant the team. Can be one of:
  # * `pull` - can pull, but not push to or administer this repository.
  # * `push` - can pull and push, but not administer this repository.
  # * `admin` - can pull, push and administer this repository.
  # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
  # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
  - name: spyglass
    permission: push

branches:
  - name: master
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true

        # Required. The list of status checks to require in order to merge into this branch
        contexts:
          - jira-lint
          - codeclimate
          - codeclimate/diff-coverage
          - codeclimate/total-coverage
          - 'security/snyk (hqo)'
          - 'license/snyk (hqo)'

      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        apps: []
        teams:
          - spyglass
